### ISSUE TITLE
Ros 2 typesupport for rosbag:: MessageInstance class

### ISSUE THREAD

**Issue by sagniknitr** [ros2/rosidl_typesupport#18]
Hi,

The current implementation of ros 2 messages use the typesupport generation to generate C++ structures  which are used to publish/subscribe to layers.I want to create a message  strucutre like the MessageInstance class of ROS 1 rosbag, so that I can send the messages stored in bag files to ROS 2 nodes.
I will be happy to receive any comment on this idea and discuss if it is feasible or not in the current version of ros 2.

Thank You.

**Comment by dirk-thomas** [comment]
The currently available API in ROS 2 doesn't allow you to publish / subscribe to an unknown type (not available on your system). In the context of implementing rosbag in ROS 2 @Karsten1987 is working on an API to allow raw binary subscriptions / publications (see ros2/demos#185). That would be necessary for the goal you have in mind.

**Comment by dirk-thomas** [comment]
I will close this question for now since the referenced ticket covers the capability to allow publishing / subscribing to arbitrary types.
