### ISSUE TITLE
Decouple idl generation pipeline from rmw implementations

### ISSUE THREAD

**Issue by ivanpauno** [ros2/rosidl_typesupport#50]
#### Feature description

Currently, [rosidl_generate_interfaces from rosidl_cmake](https://github.com/ros2/rosidl/blob/36bc907e149b1e55d76f6203d62f993158759998/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake) can't be called before the rmw implementations are built.
Decoupling idl generation from the `rmw` implementations will allow to use the same message abstractions at rmw level for implementing https://github.com/ros2/design/pull/250.

#### Implementation considerations

Currently, [rosidl_typesupport_c](https://github.com/ros2/rosidl_typesupport/blob/38eb801f1f856a503676bb79875786b3a3b6d92d/rosidl_typesupport_c/package.xml#L25) and [rosidl_typesupport_cpp](https://github.com/ros2/rosidl_typesupport/blob/38eb801f1f856a503676bb79875786b3a3b6d92d/rosidl_typesupport_cpp/package.xml#L25) have a build dependency on `rmw_implementation`,  which depends on the available implementations (see [1](https://github.com/ros2/rmw_implementation/blob/cf709e83e5d34291c52145cebf9381c7cb0f2dac/rmw_implementation/package.xml#L18-L20) [2](https://github.com/ros2/rmw_implementation/blob/cf709e83e5d34291c52145cebf9381c7cb0f2dac/rmw_implementation/package.xml#L30)).
I first believed that they depend on `rmw_implementation`, because the typesupports are being registered there (e.g.: [rmw_fastrtps_cpp](https://github.com/ros2/rmw_fastrtps/blob/099f9eed9a0f581447405fbd877c6d3b15f1f26e/rmw_fastrtps_cpp/CMakeLists.txt#L116-L118)), but I later realize that that resource isn't needed in `rmw_typesupport_*` packages nor in [rosidl_cmake](https://github.com/ros2/rosidl/blob/36bc907e149b1e55d76f6203d62f993158759998/rosidl_cmake/package.xml).
If that the case, we could simply delete that dependency.

For using the idl pipeline generation (calling `rosidl_generate_interfaces` macro), you may want to use the default generators by adding a build tool dependency on `rosidl_default_generators`, which depends on the `rmw_typesupport_*` and also in [rosidl_generator_py](https://github.com/ros2/rosidl_defaults/blob/926ce4d8f460fd8d7bb8c25544c2ebe294e691c1/rosidl_default_generators/package.xml#L15-L22). The latest, also depends on the [rmw_implementation package](https://github.com/ros2/rosidl_python/blob/1b88adf2b7add927a091b16ff08bb164f977e3cd/rosidl_generator_py/package.xml#L25), because [it is using](https://github.com/ros2/rosidl_python/blob/1b88adf2b7add927a091b16ff08bb164f977e3cd/rosidl_generator_py/cmake/rosidl_generator_py_get_typesupports.cmake#L18) the previously commented resource registered by the rmw implementations.
I think that we could avoid using that resource, and directly query [this other](https://github.com/ros2/rosidl_typesupport_fastrtps/blob/master/rosidl_typesupport_fastrtps_c/CMakeLists.txt#L61).
As I don't need the python generated file, I will only add a dependency on the packages I need instead of using `rosidl_default_generators`.

**Comment by ivanpauno** [comment]
Closing, as I've already found a way of solving the problem. See:
- https://github.com/ivanpauno/rmw_dds_common/commit/6c45d57d5629a39ce6dd4a8179e8caf3c46956d6
- https://github.com/ros2/rmw_fastrtps/pull/312

**Comment by dirk-thomas** [comment]
I will reopen this since the previous work around has reached its limits with recent changes. The goal described by this ticket is what is imo the correct approach to solve ros2/rmw_dds_common#8.

**Comment by dirk-thomas** [comment]
* [x] ros2/rmw_dds_common#12
* [x] ros2/rosidl_typesupport#62
* [ ] `rosidl_generator_py` must not depend on `rmw_implementation`: https://github.com/ros2/rosidl_python/blob/a98f9378ce345dbb4fe628723af8273210ee004a/rosidl_generator_py/package.xml#L25

**Comment by ivanpauno** [comment]
I've cancelled both linux jobs, as there are a lot of failures in the macos and Windows ones.
It seems to be related with the change in `rosidl_generator_py`.

**Comment by dirk-thomas** [comment]
The `cpplint` / `uncrustify` warnings were resolved by https://github.com/ros2/rmw_fastrtps/pull/364/commits/ff60121400229b8dae4d2d1536f66afcff63eb76.

The `flake8` warnings are unrelated and targeted by ros2/rclpy#539.
