### ISSUE TITLE
Progress toward Quality Level 1 

### ISSUE THREAD

**Issue by Blast545** [ros2/rosidl_typesupport#60]
This issue tracks the progression of packages in `rosidl_typesupport` that have been deemed necessary for Quality Level 1 and a 1.0 version. It follows the outline described in [REP 2004](https://github.com/ros-infrastructure/rep/blob/rep-2004/rep-2004.rst). 

The packages slated for Quality Level 1 for ROS 2 Foxy are:
- rosidl_typesupport_c
- rosidl_typesupport_cpp

# Progress common to all packages:
* [x] Version Policy
    - `semver` according to the recommendation for ROS Core packages in the [ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#versioning).
* [x] Version >= 1.0.0
* [x] Change Control Process
    - Recommended guidelines for ROS Core packages in the [ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#package-requirements)
* [x] API and ABI stability within a ROS distribution
* [x] Quality Declaration document for each package
* [x] Vulnerability Disclosure Policy

Documentation
* [x] Declared set of licenses
* [x] Copyright statement in each source file
    - Checked with `ament_copyright`

Platform Support
* [x] Supports all tier 1 platforms as described in [REP-2000](https://www.ros.org/reps/rep-2000.html#support-tiers)

# Progress of specific packages
## rosidl_typesupport_c

Documentation
* [x] Per-feature documentation.
* [x] Per-item documentation in public API. 
   - [x] Hosted

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
  - rcpptuils
  - rosidl_runtime_c
  - rosidl_typesupport_connext_c
  - rosidl_typesupport_interface
  - rosidl_typesupport_introspection_c
* [x] Non-ROS dependencies are equivalent level 1
  - None

Testing:
* [x] Must have system tests which cover all items in the "feature" documentation
* [x] Must have system, integration, and/or unit tests which cover all of the public API
* [x] Code Coverage > 95%:
  - * [x] Must have code coverage tracking for the package -> [here](https://ci.ros2.org/job/ci_linux_coverage/lastSuccessfulBuild/cobertura/)
  - * [x] Must have and enforce a code coverage policy for new changes [Policy](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#code-coverage)
* [x] Performance tests: not currently available.
* [x] Linters and Static Analysis:
  - * [x] Must have a code style and enforce it.
  - * [x] Must use static analysis tools where applicable: 
  -- See [Linters ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#linters)

## rosidl_typesupport_cpp
Documentation
* [x] Per-feature documentation.
* [x] Per-item documentation in public API. 
   - [x] Hosted

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
  - rcpptuils
  - rosidl_runtime_c
  - rosidl_typesupport_connext_c
  - rosidl_typesupport_interface
  - rosidl_typesupport_introspection_c
* [x] Non-ROS dependencies are equivalent level 1
  - None

Testing:
* [x] Must have system tests which cover all items in the "feature" documentation
* [ ] Must have system, integration, and/or unit tests which cover all of the public API
* [x] Code Coverage > 95%:
  - * [x] Must have code coverage tracking for the package -> [here](https://ci.ros2.org/job/ci_linux_coverage/lastSuccessfulBuild/cobertura/)
  - * [x] Must have and enforce a code coverage policy for new changes [Policy](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#code-coverage)
* [x] Performance tests: not currently available.
* [x] Linters and Static Analysis:
  - * [x] Must have a code style and enforce it.
  - * [x] Must use static analysis tools where applicable: 
  -- See [Linters ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#linters)

**Comment by chapulina** [comment]
Both packages are now level 1: https://github.com/ros2/rosidl_typesupport/pull/96
