### ISSUE TITLE
Same header file hosted in two packages: type_support_map.h

### ISSUE THREAD

**Issue by j-rivero** [ros2/rosidl_typesupport#79]
#### Feature description

The repository hosts a copy of the same file `type_support_map.h` in the two packages [rosidl_typesupport_c](https://github.com/ros2/rosidl_typesupport/blob/master/rosidl_typesupport_c/include/rosidl_typesupport_c/type_support_map.h) and  [rosidl_typesupport_cpp](https://github.com/ros2/rosidl_typesupport/blob/master/rosidl_typesupport_cpp/include/rosidl_typesupport_cpp/type_support_map.h). Not sure if that respond to a design decision or we could make `rosidl_typesupport_cpp` to use the one in `rosidl_typesupport_c`.

My first intention to change the code to implement that idea finished in a success build but before sending the PR I want to be sure that we want to go with it.

**Comment by dirk-thomas** [comment]
> My first intention to change the code to implement that idea finished in a success build but before sending the PR I want to be sure that we want to go with it.

I don't understand the specific proposal but I don't see a reason why the definition of that struct couldn't be deduplicated. Please go ahead and propose a PR.

**Comment by dirk-thomas** [comment]
@j-rivero What is the status on this?

**Comment by j-rivero** [comment]
pull request is ready to review https://github.com/ros2/rosidl_typesupport/pull/81, just need some fixes in infrastructure to pass AFAIK.
